lib1 = input("Enter a insult: ")
lib2 = input("Enter an insulting word: ")
lib3 = input("Enter an adjective: ")
lib4 = input("Enter a verb: ")
print("\033[1;35;40m black")
print("John was a " + lib1)
print("His mother was also a " + lib2)
print("He lived a " + lib3 + " life.")
print("He doesn't even know how to " + lib4 + " anymore.")

sad = input("Are you sad?: ")
sad1 = input("It's ok, I understand ")
sad2 = input("So you're a coward huh? ")
sad3 = input("Dumb weak ")
sad4 = input("Your a dumb weak small person ")
